paths: 
  raw_data: data/${dataset.subset}/raw
  test_data: data/${dataset.subset}/test
  noise_data: data/${dataset.subset}/noise
  source_separated_data: data/${dataset.subset}/source_separated
  birdnetlib_analyzed_data: data/${dataset.subset}/birdnetlib_analyzed
  segmented_data: data/${dataset.subset}/segmented
  balanced_data: data/${dataset.subset}/balanced
  polyphonic_data: data/${dataset.subset}/polyphonic

random:
  random_seed: 42

dataset:
  subset: HSN

source_separation:
  model_dir: resources/bird_mixit_model_checkpoints/output_sources4
  checkpoint: resources/bird_mixit_model_checkpoints/output_sources4/model.ckpt-3223090
  onnx_model_path: resources/bird_mixit_onnx/model.onnx
  onnx_optimized_model_path: resources/bird_mixit_onnx/model_optimized.onnx

segmentation:
  segment_length_in_s: 5

mix:
  max_polyphony_degree: 6
  signal_levels: [-12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]
  snr_values: [-12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  mix_levels: [-12, -11, -10, -9, -8, -7, -6]